-- PostgreSQL database dump
--

-- Dumped from database version 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
-- Dumped by pg_dump version 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: courses; Type: TABLE; Schema: public; Owner: myapp
--

CREATE TABLE public.courses (
id integer NOT NULL,
name character varying NOT NULL,
description character varying NOT NULL,
price integer NOT NULL
);


ALTER TABLE public.courses OWNER TO myapp;

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: myapp
--

CREATE SEQUENCE public.courses_id_seq
AS integer
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;


ALTER TABLE public.courses_id_seq OWNER TO myapp;

--
-- Name: courses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: myapp
--

ALTER SEQUENCE public.courses_id_seq OWNED BY public.courses.id;


--
-- Name: projects; Type: TABLE; Schema: public; Owner: myapp
--

CREATE TABLE public.projects (
id integer NOT NULL,
title character varying NOT NULL,
instructions character varying NOT NULL,
course_id integer NOT NULL
);


ALTER TABLE public.projects OWNER TO myapp;

--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: myapp
--

CREATE SEQUENCE public.projects_id_seq
AS integer
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;


ALTER TABLE public.projects_id_seq OWNER TO myapp;

--
-- Name: projects_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: myapp
--

ALTER SEQUENCE public.projects_id_seq OWNED BY public.projects.id;


--
-- Name: courses id; Type: DEFAULT; Schema: public; Owner: myapp
--

ALTER TABLE ONLY public.courses ALTER COLUMN id SET DEFAULT nextval('public.courses_id_seq'::regclass);


--
-- Name: projects id; Type: DEFAULT; Schema: public; Owner: myapp
--

ALTER TABLE ONLY public.projects ALTER COLUMN id SET DEFAULT nextval('public.projects_id_seq'::regclass);


--
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: myapp
--

COPY public.courses (id, name, description, price) FROM stdin;
1	Full Stack	Become a Full Stack Developer with this course	249
2	Android	Become an Android Developer	239
\.


--
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: myapp
--

COPY public.projects (id, title, instructions, course_id) FROM stdin;
1	Capstone	Build your own project using all you have learned during the course	1
2	Trivia	Build a trivia app	1
\.


--
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myapp
--

SELECT pg_catalog.setval('public.courses_id_seq', 2, true);


--
-- Name: projects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myapp
--

SELECT pg_catalog.setval('public.projects_id_seq', 2, true);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: myapp
--

ALTER TABLE ONLY public.courses
ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: myapp
--

ALTER TABLE ONLY public.projects
ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: projects projects_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: myapp
--

ALTER TABLE ONLY public.projects
ADD CONSTRAINT projects_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- PostgreSQL database dump complete
--
